name: 522_docker_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python[version='>=3.11,<3.13']
  - altair=5.5
  - vegafusion-python-embed=1.6.9
  - numpy=1.26
  - shap[version='>=0.45']
  - matplotlib
  - pandas=2.2
  - tabulate=0.9.0
  - vegafusion=1.6.9
  - scikit-learn
  - vl-convert-python[version='>=1.7.0']
  - jupyterlab=4.0
  - pip
  - pandera
